### ISSUE TITLE
Коммиты ниочем

### ISSUE THREAD

**Issue by KineticCookie** [Ainaz/MailServer#1]
Коммиты ниочем вообще.

---
56f970e2a6a50bd4f44b7a5bb9b68111e05519ed
cf1978075c831e0cd95491b784a4f4832d29a739
6dbd9c9f0473e9f4341b41988a9638e1ae9f6983
181f3284646731db4214fbdec383917b8b44fd06
c3ade556dc75af319e72a5b344718f68cc6332d3

**Comment by Ainaz** [comment]
Добавил новый сли интересно)коммит, в котором добавил скелет приложения, позырь, если интересно) 9ace20f27f4dbce587c76641f3986d5068e958b1
